name: Quiz
services:
    redis:
        image: redis:latest
        container_name: quizRedis
        restart: always
        ports:
            - 6379:6379
        # volumes:
        #     - redis-data:/data
    # postgres:
    #     image: postgres:17.3
    #     container_name: quizPostgres
    #     restart: always
    #     environment:
    #         POSTGRES_PASSWORD: 123
    #         POSTGRES_USER: postgres
    #         POSTGRES_DB: Quiz
    #     ports:
    #         - 5433:5432
    #     volumes:
    #         - postgres-data:/var/lib/postgres/data
    backend:
        image: nguyentienminh0710/quizv2:0.0.1
        container_name: quizBE
        restart: always
        env_file: ".env"
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: host.docker.internal
        ports:
            - 8080:8080
        depends_on:
            # - postgres
            - redis
        # volumes:
        #     - backend-data:/app/data
# volumes:
#     redis-data:
#     postgres-data:
#     backend-data: